# Generated by Django 5.1 on 2025-05-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='admission_notice')),
                ('ordering_number', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ordering_number'],
            },
        ),
    ]
