# Generated by Django 5.1 on 2025-05-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_academicqualification_payment_personalinformation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RollNumberSeed',
            new_name='StartingRoll',
        ),
    ]
