# Generated by Django 5.1 on 2025-05-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_rename_rollnumberseed_startingroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
