# Generated by Django 5.1 on 2025-05-12 07:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_delete_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_image', models.ImageField(default='applicant_img', upload_to='photos/')),
                ('applicant_sig', models.ImageField(default='applicant_img', upload_to='signatures/')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
