# Generated by Django 5.1 on 2025-05-18 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_alter_personalinformation_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionnotice',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
