# Generated by Django 5.1 on 2025-05-19 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_maingallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maingallery',
            name='chairman',
        ),
        migrations.RemoveField(
            model_name='maingallery',
            name='chairman_message',
        ),
        migrations.RemoveField(
            model_name='maingallery',
            name='co_ordinator',
        ),
        migrations.RemoveField(
            model_name='maingallery',
            name='co_ordinator_message',
        ),
        migrations.RemoveField(
            model_name='maingallery',
            name='department_description',
        ),
        migrations.RemoveField(
            model_name='maingallery',
            name='department_img',
        ),
        migrations.RemoveField(
            model_name='maingallery',
            name='faculties',
        ),
        migrations.RemoveField(
            model_name='maingallery',
            name='founded',
        ),
        migrations.RemoveField(
            model_name='maingallery',
            name='passed_students',
        ),
        migrations.RemoveField(
            model_name='maingallery',
            name='students',
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_description', models.TextField(blank=True, null=True)),
                ('department_img', models.ImageField(blank=True, null=True, upload_to='department_img/')),
                ('chairman_message', models.TextField(blank=True, null=True)),
                ('co_ordinator_message', models.TextField(blank=True, null=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('faculties', models.IntegerField(blank=True, null=True)),
                ('students', models.IntegerField(blank=True, null=True)),
                ('passed_students', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chairman', to=settings.AUTH_USER_MODEL)),
                ('co_ordinator', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_ordinator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
