# Generated by Django 5.1 on 2025-05-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
