# Generated by Django 5.1 on 2025-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userregistration_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('manager', 'Manager'), ('student', 'Student'), ('accountant', 'Accountant'), ('applicant', 'Applicant')], max_length=40),
        ),
    ]
