# Generated by Django 5.1 on 2025-05-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userregistration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
