# Generated by Django 5.1 on 2025-05-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userregistration_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='position_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
